name: openbudget_client
description: Starting point for a Serverpod client.
version: 0.1.0

environment:
  sdk: ^3.11.0

resolution: workspace

dependencies:
  serverpod_auth_idp_client: 3.4.6
  serverpod_client: 3.4.6

dev_dependencies:
  openbudget_lints:
    path: ../openbudget_lints
